@baseUrl = http://127.0.0.1:8000

# ==========================================================
# --- Secao02 ---
# ==========================================================

### Raiz
# @name RaizEndpoint
GET {{baseUrl}}/msg
Content-Type: application/json

