@baseUrl = http://127.0.0.1:8000

# ==========================================================
# --- Secao02 ---
# ==========================================================
### Cursos/
# @name Cursos
POST {{baseUrl}}/cursos
Content-Type: application/json

{
    "titulo": "Curso de FastAPI",
    "aulas": 30,
    "horas": 10
}
### Cursos
# @name Cursos
GET {{baseUrl}}/cursos
Content-Type: application/json

### Cursos/{curso_id}
# @name Cursos id
GET {{baseUrl}}/cursos/2
Content-Type: application/json

### Cursos/{curso_id}
# @name Cursos Update
PUT {{baseUrl}}/cursos/4
Content-Type: application/json

{
    "titulo": "Curso de FastAPI - Atualizado",
    "aulas": 25,
    "horas": 12
}


### Cursos/{curso_id}
# @name Cursos Delete

DELETE {{baseUrl}}/cursos/3
Content-Type: application/json
